server:
  port: 8083

spring:
  application:
    name: servicio-inventario
  datasource:
    url: jdbc:postgresql://localhost:5432/inventario_db
    username: postgres
    password: 23May@2004
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  cloud:
    stream:
      # La configuración de los consumidores se mantiene
      function:
        definition: manejarProductoCreado;manejarProductoEliminado;manejarVentaRegistrada
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    com.agrominerva.inventario: DEBUG
    org.springframework.kafka: DEBUG

# URL del servicio que recibirá la notificación de stock actualizad
app:
  servicios:
    productos:
      url: http://localhost:8084 # Cambia esto por la URL real