spring:
  application:
    name: servicio-usuarios
  datasource:
    # Conecta a la base de datos de usuarios
    url: jdbc:postgresql://postgres_usuarios:5432/usuarios_db
    username: postgres
    password: TE22003

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      # 'update' es bueno para desarrollo
      ddl-auto: update
    # Muestra el SQL en la consola
    show-sql: true

  # --- Configuración de Kafka (Básica) ---
  kafka:
    # Solo necesita saber dónde está el bróker de Kafka
    bootstrap-servers: localhost:9092

server:
  port: 8080