spring:
  application:
    name: servicio-usuarios
  datasource:
    # Conecta a la base de datos de usuarios
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      # 'update' es bueno para desarrollo
      ddl-auto: update
    # Muestra el SQL en la consola
    show-sql: true

  # --- Configuración de Kafka (Básica) ---
  kafka:
    # Solo necesita saber dónde está el bróker de Kafka
    bootstrap-servers: localhost:9092

server:
  port: 8080